# netlify.toml

[build]
  command = "npm run build"  # Replace with your build command
  publish = "dist"          # Replace with your build output directory

[[redirects]]
  from = "/homepage*"
  to = "/index.html"
  status = 200
